### PR TITLE
Broken github URL, formatting fixes

### PR DESCRIPTION
**Pull request by jhannah**

### CODE REVIEW

**Comment by jjn1056** [comment]
thanks!  I'll try to send it over to the main advent website when I get a break --john

**Comment by jhannah** [comment]
Thanks. :) Should look better once you push: http://www.catalystframework.org/calendar/2013/26

**Comment by jhannah** [comment]
... can you leave this open until the push happens?

**Comment by jjn1056** [comment]
Hey,

I' can't seem to get issues to reopen, can you give it a try? --john

On Tuesday, February 4, 2014 9:35 AM, Jay Hannah notifications@github.com wrote:

... can you leave this open until the push happens?

**Comment by jhannah** [comment]
Can't seem to re-open this one, so I opened a new one which references this one. Thanks! :)

**Pull request merged**
